In [ ]:
#Default array float type .


In [3]:
#NumPy=numeric python 
import numpy  as np
print(np.__version__)

2.3.4


In [6]:
import numpy as np
a=[1,2,3]
b=[[1,2,3],[4,5,6]]
print(a,b)

[1, 2, 3] [[1, 2, 3], [4, 5, 6]]


In [17]:
arr = np.array([[1,2,3],[4,5,6]])
arr.ndim #2
arr.shape #(2,3)
arr.size #6
arr.dtype 
arr.itemsize #8
arr.nbytes #48

48

# Array create buildin function

In [18]:
#Zero Array
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
#Ones Array
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [26]:
# Random Number
np.random.rand(3,3)
np.random.randint(1,10,(3,4))

array([[3, 6, 9, 3],
       [8, 1, 1, 8],
       [3, 6, 6, 1]], dtype=int32)

In [29]:
#Range
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [46]:
#Linspace
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [41]:
#identify matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
#identity
np.identity(4)  #correct
np.identity(3,4)  #error

TypeError: Cannot interpret '4' as a data type

In [51]:
#diagonal
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

# December

In [29]:
#1D array
import numpy as nd
arr=nd.array([1,2,3])
print(arr)
print(arr.shape) 
print(arr.dtype)# tin element

[1 2 3]
(3,)
int64


In [15]:
# 2D array
arr=nd.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)  #(2 row and 3 column

[[1 2 3]
 [4 5 6]]
(2, 3)


In [18]:
#3d array
arr = nd.array([[[1,2,3],[3,4,3]], [[5,6,3],[7,8,3]]])
print(arr)
print(arr.shape)# (2 layer,2 row ,3 column)

[[[1 2 3]
  [3 4 3]]

 [[5 6 3]
  [7 8 3]]]
(2, 2, 3)


In [19]:
#arr.ndim(number of dimention)
arr=nd.array([[1,2,3],[4,5,6]])
print(arr.ndim)  #dimention


2


In [27]:
#arr.size   total number of element  #size=row*column    10,20,30,40   4 element 
#arr=nd.array([[1,2,3],[4,5,6],[1,3,2]])
arr=nd.array([10,20,3,40,50])
print(arr.size)


5


In [28]:
arr.dtype

dtype('int64')

In [33]:
#Example: 6 elements  dtype = int64 (8 bytes)   So memory = 6 × 8 = 48 bytes
#nbytes
arr=nd.array([[1,2,3],[3,4,4]])
print(arr.nbytes)

48


In [36]:
#1) np.zeros(shape)
nd.zeros([2,3])
nd.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
# 3) np.full(shape, value)
nd.full([2,3],7)

array([[7, 7, 7],
       [7, 7, 7]])

In [41]:
# np.eye(n)
#Identity matrix banata hai.
nd.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
#np.arange(start, stop, step) Range function ka NumPy version (fast)
#arange
a=nd.arange(1,10,3)
print(a)

[1 4 7]


In [47]:
# ) np.linspace(start, stop, num_steps) . Equal spaced numbers banata hai.
a=nd.linspace(0,1,5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


In [49]:
# np.random.random(shape) 0 or 1 k bich ka random deta h
nd.random.random(4)

array([0.07054581, 0.24279866, 0.95054947, 0.13902875])

In [52]:
#np.random.randint(low, high, size)
nd.random.randint(1,10,2)

array([2, 2], dtype=int32)

# Indexing & Slicing

In [55]:
# Indexing = specific value pick karna Slicing = portion pick karna
arr=nd.array([10,20,30,40])
print(arr[-1])

40


In [63]:
# 2D indexing
arr=nd.array([[1,2,3],[4,5,6]])
arr[0,2]


np.int64(3)

In [68]:
arr=nd.array([[1,2,3],[4,5,6],[6,7,8]])
print(arr[0:2,1:3])

[[2 3]
 [5 6]]


In [72]:
# Boolean Indexing (Detailed)
#Agar array me conditions lagani ho:
arr=nd.array([20,14,65,3,7,55])
#print(arr[arr>14])
#print(arr[arr%2==0])
print(arr[arr%5==0])

[20 65 55]


# Vectorized Operations (WHY NumPy is FAST)

In [75]:
#python m jese loop use krte hen operation perform krne ko but in the numpy loop ki requirement nhi h 
#python
arr=[1,2,3]
for i in arr:
    i=i*2
    print(i)

#numpy
arr=nd.array([1,2,3])
a=arr+10
print(a)
print(arr*2)

2
4
6
[11 12 13]
[2 4 6]


In [78]:
arr=[1,2,3,4,5]
s=nd.sum(arr)
m=nd.min(arr)
me=nd.mean(arr)
mx=nd.max(arr)
d=nd.std(arr)
print(s,m,me,mx,d)

15 1 3.0 5 1.4142135623730951


In [82]:
# create array 1,51
import numpy as np
c=np.arange(1,51+1,1)
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51]


In [ ]:
# # Q2: Indexing
# Given:
# arr = np.array([5,10,15,20,25,30,35])

# Find:
# 20
# Last element
# First 3 elements
# Elements from index 2 to 5


In [88]:
arr=np.array([5,10,15,20,25,30,35])
#arr[-1]
#arr[:3]
#arr[2:6]
arr[3]

np.int64(20)

In [95]:
# 2 d array create
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
#shape,element,row,column
print(arr.shape)
print(arr.size)
print(arr[0,2])
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
6
3
2


In [98]:
# Q4: Boolean Filtering
# Array:
# arr = np.array([12, 3, 45, 7, 22, 90, 11])
# Find:
# sab numbers > 10
# sab even numbers
# sab numbers divisible by 3
arr=np.array([12,3,45,7,22,90,11])
g_10=arr[arr>10]
print(g_10)
e=arr[arr%2]
print(e)
nd3=arr[arr%3]
print(nd3)

[12 45 22 90 11]
[12  3  3  3 12 12  3]
[12 12 12  3  3 12 45]


In [110]:
# arr = np.array([2,4,6,8,10])
#Find:
Sum=np.sum(arr)
Mean=np.mean(arr)
Max=np.max(arr)
p=arr * 3
q=arr ** 2
print(q)

[ 144    9 2025   49  484 8100  121]


In [127]:
# Q6: Random Matrix
# np.random.randint() se 3x3 matrix banao (1–100 range).
# Print:
# Total elements (size)
# Memory used (nbytes)
# Matrix ka 2nd row
arr=np.random.randint(1,100,size=(3,3))
print(arr)
s=arr.size
print(s)
nb=arr.nbytes
print(nb)
print(arr[1:2])

[[15 92 65]
 [78 63 40]
 [ 1 22 35]]
9
36
[[78 63 40]]


In [139]:
# Q7: Slicing 2D
# Matrix:
# [[10,20,30,40],
#  [50,60,70,80],
#  [90,100,110,120]]
# Find:
# 70
# First 2 rows
# Last column
# Middle 2x2 block:

arr=np.array([[10,20,30,40],
             [50,60,70,80],
             [90,100,110,120]])
print(arr[1,2])
print(arr[:2])
print(arr[:,3])
print(arr[1:3,1:3])

70
[[10 20 30 40]
 [50 60 70 80]]
[ 40  80 120]
[[ 60  70]
 [100 110]]


In [140]:
# Q8: linspace
# Use:
# np.linspace(0, 1, 6)
# Find:
# Output kya hoga?
# Kitne steps banenge?
# Difference between values?
arr=np.array([1,2,3,4,5,6,7])
s=np.linspace(0,1,6)
print(s)

[0.  0.2 0.4 0.6 0.8 1. ]


In [141]:
#Q9: Create Identity Matrix
#np.eye(5) ka output draw karo (line by line).
print(np.eye(5))



[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# Q10: Full Array
# np.full((3,4), 9) banao.
# Then:
# Shape
# ndim
# last row print karo

In [148]:
n=np.full((3,4),5)
s=n.shape
print(s)
nd=n.ndim
print(nd)
print(n[-1])

(3, 4)
2
[5 5 5 5]


In [151]:
# Q1. Create an array from 100 to 150 (step = 5).
#Example: [100, 105, 110 ...]
arr=np.arange(100,151,5)
print(arr)

[100 105 110 115 120 125 130 135 140 145 150]


In [152]:
# Q2. Given array:
arr = np.array([4, 8, 12, 16, 20, 24])
print(arr[1])
print(arr[-2])
print(arr[1:5])
# Find:
# Second element
# Last 2 elements
# Elements at index 1 to 4

8
20
[ 8 12 16 20]


In [170]:
# Q3. Create a 2D array 4×3 (1–12 range).
print(np.random.randint(1,12,(4,3)))


[[4 5 7]
 [2 5 6]
 [9 9 4]
 [3 7 2]]


In [174]:
arr = np.array([12, 45, 3, 89, 6, 90, 22])
#Numbers > 20,Even numbers,Numbers divisible by 5
print(arr[arr>20])
print(arr[arr%2==0])
print(arr[arr%5==0])

[45 89 90 22]
[12  6 90 22]
[45 90]


In [188]:
arr=np.array([[10, 20, 30, 40],
 [50, 60, 70, 80],
 [90,100,110,120],
 [130,140,150,160]]
)
#First column
print(arr[:,:1])
#Last row
print(arr[-1])
#Middle 2×2 block
print(arr[1:3,1:3])
#Elements 70, 100 ko slice se nikaalo (print individually
print(arr[1,2])
print(arr[2,1])

[[ 10]
 [ 50]
 [ 90]
 [130]]
[130 140 150 160]
[[ 60  70]
 [100 110]]
70
100


In [ ]:
# Q6. Find:
# arr = np.array([3, 6, 9, 12, 15, 18])
# Sum
# Mean
# Min
# Max
# Standard deviation

In [5]:
import numpy as np
arr = np.array([3, 6, 9, 12, 15, 18])
s=arr.sum()
print(s)
m=arr.mean()
mi=arr.min()
ma=arr.max()
st=arr.std()
print(m,mi,ma,st)

63
10.5 3 18 5.123475382979799


# 03/12/2025

In [7]:
arr=np.array((1,2,3,4))
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [10]:
arr=np.array(45)
print(arr)

45


In [15]:
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,6],[3,4,5]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 6]
  [3 4 5]]]


In [19]:
a0=np.array(30)
a1=np.array([12,7,3,4,5])
a2=np.array([[1,2,3],[4,5,6]])
a3=np.array([[[1,2],[3,4]],[[4,5],[6,7]]])
print(a0.ndim)
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

0
1
2
3


In [21]:
arr=np.array([1,2,3,4],ndmin=5)
print(arr)

[[[[[1 2 3 4]]]]]


In [22]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[2]+arr[3])

7


In [25]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2D Array:',arr[1,2])

2D Array: 8


In [30]:
arr = np.array([1, 2, 3, 4],dtype='i4')
print(arr.dtype)

int32


In [39]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [38]:
arr = np.array([1.1, 2.1, 3.1],dtype='i')
print(arr)

[1 2 3]


In [46]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a=(arr.reshape(2,4).base)
print(a)

[1 2 3 4 5 6 7 8]


In [48]:
arr=[[1,2,3],[4,5,6]]
for i in arr:
    for j in i:
        print(j)

1
2
3
4
5
6


In [53]:
arr=np.array([[1,2,3],[4,5,6]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6


In [55]:
arr=[1,2,3,4,5]
for ind,x in np.ndenumerate(arr):
    print(ind,x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5


In [70]:
a1=np.array([1,2,3,4])
a2=np.array([5,6,7,8])
arr=np.concatenate((a1,a2),axis=0)
print(arr)

[1 2 3 4 5 6 7 8]


In [68]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [72]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])
arr=np.hstack((arr1,arr2))

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [76]:
a=np.array([1,2,3])
b=np.array([4,5,6])
arr=np.hstack((a,b))
arrv=np.vstack((a,b))
darr=np.dstack((a,b))
print(arr)
print(arrv)
print(darr)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


# splitting

In [87]:
import numpy as np
arr=[12,3,4]
ass=np.array_split(arr,4)
print(ass)

[array([12]), array([3]), array([4]), array([], dtype=int64)]


In [88]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [89]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
ar=np.array_split(arr,3)
print(ar)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [91]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
ass=np.array_split(arr,3)
print(ass)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [92]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [96]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr=np.hsplit(arr,3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# Searching 

In [102]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5,6,7,8,9,10])

x = np.where(arr%2==1)

print(x)


(array([0, 2, 4, 6, 8]),)


In [116]:
#searchsorted
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
x=np.searchsorted(arr,5)
print(x)

4


In [133]:
arr=np.array([6,7,8,9])
x=np.searchsorted(arr,8,side="right")
print(x)

3


In [134]:
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)

[1 2 3]


In [137]:
# Sort
arr=np.array([3,4,5,8,6,1])
print(np.sort(arr))

[1 3 4 5 6 8]


In [138]:
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [139]:
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [140]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
s=np.sort(arr)
print(s)

[[2 3 4]
 [0 1 5]]


In [141]:
arr=np.array([10,34,2,56,67])
x=np.array([True,False,False,True,True])
newarr=arr[x]
print(newarr)

[10 56 67]


In [142]:
arr=np.array([40,21,42,43,45,50])
filter_arr=[]
for i in arr:
    if i >42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
print(filter_arr)
print(arr[filter_arr])

[False, False, False, True, True, True]
[43 45 50]


In [149]:
arr=np.array([2,3,4,5,6,7,8,9,24,35,65,60])
filter_arr=[]
for i in arr:
    if i %2==0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
print(filter_arr)
print(arr[filter_arr])

[True, False, True, False, True, False, True, False, True, False, False, True]
[ 2  4  6  8 24 60]


In [150]:
arr=np.array([2,3,4,5,6,7])
filter_arr=arr>4
print(filter_arr)
print(arr[filter_arr])

[False False False  True  True  True]
[5 6 7]


# #####################RANDOM###########################

In [205]:
from numpy import random
arr=random.randint(100)
print(arr)
arrr=random.randint(100,size=5)
print(arrr)
#2Darray with size
a=random.randint(100,size=(2,3))
print(a)

33
[90  8 27 43 35]
[[78 75 22]
 [76 17 30]]


In [208]:
arr=random.rand()
print(arr)
a=random.rand(5,3)
print(a)

0.3039278873330108
[[0.93281807 0.06920282 0.35810473]
 [0.9244757  0.29297933 0.37317161]
 [0.42560442 0.50276944 0.3793949 ]
 [0.13521946 0.79605645 0.11294262]
 [0.87086555 0.58267811 0.99211111]]


In [215]:
arr=random.choice([2,3,6,4,9])
print(arr)

9


In [225]:
arr=random.choice([2,3,4,5,86,5,9,3],size=(2,3))
print(arr)

[[3 3 4]
 [3 2 5]]


In [232]:
#ONES
arr=np.ones((2,3))
print(arr)
ar=np.zeros((3,3))
print(ar)
a=np.full((5,6),9)
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[9 9 9 9 9 9]
 [9 9 9 9 9 9]
 [9 9 9 9 9 9]
 [9 9 9 9 9 9]
 [9 9 9 9 9 9]]


In [249]:
p=np.arange(10,51,5)
print(p)

[10 15 20 25 30 35 40 45 50]


In [267]:
p=np.linspace(0,1,6)
print(p)

[0.  0.2 0.4 0.6 0.8 1. ]


In [268]:
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [281]:
from numpy import random as r
a=np.random.randint(1,10)
print(a)

8


In [292]:
rng = np.random.default_rng()
a=rng.integers(1, 10)
print(a)

6


In [316]:
rng=np.random.default_rng(34)
a=rng.integers(1,10,size=5)
print(a)

[1 1 2 8 2]


In [317]:
r=np.random.default_rng()
print(rng.random(5))

[0.6510613  0.48409238 0.78853349 0.88072257 0.899722  ]


In [ ]:
r=np.random.default_rng()
print(r)

In [21]:
from numpy import random
arr = np.array([10, 20, 30, 40, 50])
print(random.choice(arr))

20


In [35]:
rng = np.random.default_rng()
new_arr = rng.permutation(arr)
print(new_arr)


[10 20 40 50 30]


In [46]:
rng = np.random.default_rng()
data = rng.normal(loc=50, scale=10, size=5)
print(data)

[ -1.87877303  -1.94107167   4.51643226 -17.22879457   8.04269103]
